server:
  port: 8090


spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-aouto: create-drop
        default_fetch_size: 20
        jdbc.batch_size: 20
        id.new_generator_mappings: false

    defer-datasource-initialization: true

  datasource:
    # ImMemory
    # This url we use to connect in web console
    url: jdbc:h2:mem:database_h2
    # This url we use to connect H2 in IDEA
    # TCP:  jdbc:h2:tcp://localhost:9092/mem:database_h2
    username: root
    password: 1234

  h2.console.enabled: true


